### PR TITLE
tooltip callbacks

### PR DESCRIPTION
**Pull request by macias**
Few notes:
* this commit breaks (silently) API (Chart became IDisposable),
* I wish I know how to pass private property for serialization in order to make Callbacks cleaner, but apparently System.Text.Json still lags behind Newtonsoft,
* I cannot run solution because it seems now it requires higher runtime (was it necessary?), I could build it though, and I ran my own code with using changed code. So it should work, but please check it (i.e. run the demo).

I hope I will sort runtime soon so I will be able to test changes fully.

### CODE REVIEW

**Comment by erossini** [comment]
I use `System.Text,Json` to avoid too many external dependencies. What private property do you want to pass? Why do those properties be private?

I noticed that if you use Microsoft Edge, the application takes a lot of time to start and it shows only the _Loading..._ message. If you use Firefox, the application starts immediately.

Let me have a look.

**Comment by erossini** [comment]
What does it mean requires higher runtime?

**Comment by erossini** [comment]
I have a question for you. I like to have the opportunity to add custom code when Chartjs renders the graph. The problem I face is that Chartjs calls my function but it doesn't pass all the parameters. Do you have try something like that?

**Comment by erossini** [comment]
The demo is working for me.

PS: I'm planning on update ChartJs to the latest version 3.9.1

**Comment by macias** [comment]
> What private property do you want to pass? Why do those properties
> be private?

I wanted to make "HasLabel" private because it is meant only to JS code, not for C#. It is minor thing, but still I don't like cases when some framework enforces some arbitrary behavior on me.

> What does it mean requires higher runtime?

Previously the packages you used required RT 6.0.8, now you upgraded the packages and with it the requirement is RT 6.0.10.

> I like to have the opportunity to add
> custom code when Chartjs renders the graph. The problem I face is
> that Chartjs calls my function but it doesn't pass all the
> parameters. Do you have try something like that?

Well, I am sending data from JS to C# and it works. All parameters have to be serializable, so maybe you are sending something that cannot be created/deserialized on C# side?

> The demo is working for me.

Good news :-). Thank you.

> PS: I'm planning on update ChartJs to the latest version 3.9.1

Please note the numbering is broken in ChartJs. Despite the numbers, 3.9.1 is not compatible with 3.7.1.

**Comment by erossini** [comment]
Thank you @macias.

I don't have any idea how to help with the private property.
I think we can fix it to downgrade the RT if this helps.

### JS interaction
What I mean is different. This is a bit long.

Look at the following code:

```js
 <canvas id="myChart1" height="300" width="500"></canvas>
 <canvas id="myChart2" height="300" width="500"></canvas>
    
 var chartData = {
     labels: ["January", "February", "March", "April", "May", "June"],
     datasets: [
         {
             fillColor: "#79D1CF",
             strokeColor: "#79D1CF",
             data: [60, 80, 81, 56, 55, 40]
         }
     ]
 };
    
 var ctx = document.getElementById("myChart1").getContext("2d");
 var myLine = new Chart(ctx).Line(chartData, {
     showTooltips: false,
     onAnimationComplete: function () {
    
         var ctx = this.chart.ctx;
         ctx.font = this.scale.font;
         ctx.fillStyle = this.scale.textColor
         ctx.textAlign = "center";
         ctx.textBaseline = "bottom";
    
         this.datasets.forEach(function (dataset) {
             dataset.points.forEach(function (points) {
                 ctx.fillText(points.value, points.x, points.y - 10);
             });
         })
     }
 });
    
 var ctx = document.getElementById("myChart2").getContext("2d");
 var myBar = new Chart(ctx).Bar(chartData, {
     showTooltips: false,
     onAnimationComplete: function () {
         var ctx = this.chart.ctx;
         ctx.font = this.scale.font;
         ctx.fillStyle = this.scale.textColor
         ctx.textAlign = "center";
         ctx.textBaseline = "bottom";
    
         this.datasets.forEach(function (dataset) {
             dataset.bars.forEach(function (bar) {
                 ctx.fillText(bar.value, bar.x, bar.y - 5);
             });
         })
     }
 });
    
 var ctx = document.getElementById("myChart2").getContext("2d");
 var myBar = new Chart(ctx).Bar(chartData, {
     showTooltips: false,
     onAnimationComplete: function () {
         var ctx = this.chart.ctx;
         ctx.font = this.scale.font;
         ctx.fillStyle = this.scale.textColor
         ctx.textAlign = "center";
         ctx.textBaseline = "bottom";
    
         this.datasets.forEach(function (dataset) {
             dataset.bars.forEach(function (bar) {
                 ctx.fillText(bar.value, bar.x, bar.y - 5);
             });
         })
     }
 });
```

This code generates those graphs

image

If you see, both graphs use `onAnimationComplete` to add some extra data in the graph (in this case the labels). My initial idea was to allow developers to add their own code. For that, I added a property in the Blazor component `onAnimationComplete` that should be the name of the JavaScript function you place in the `index.html` in Blazor to add your customization.

For example, I tried to add this code in the component

    chart.options.animation.onComplete = function (ctx) {
        window["AnimationComplete1"](ctx);
        DotNet.invokeMethodAsync('PSC.Blazor.Components.Chartjs', 'AnimationCompleted');
    }

    chart.options.scales.x.ticks.callback = function (val, index) {
        window["TickEvent1"](val, index);
        DotNet.invokeMethodAsync('PSC.Blazor.Components.Chartjs', 'ChartScaleXTicks', val, index);
    }

In the `index.html` I added the JavaScript functions

```js
function AnimationComplete1(ctx) {
         ctx.font = this.scale.font;
         ctx.fillStyle = this.scale.textColor
         ctx.textAlign = "center";
         ctx.textBaseline = "bottom";
    
         this.datasets.forEach(function (dataset) {
             dataset.bars.forEach(function (bar) {
                 ctx.fillText(bar.value, bar.x, bar.y - 5);
             });
         })
}

function TickEvent1(val, index) {
}
```

The problem I faced was that the `ctx` properties are not available in the function. So, if I want to add some custom code, I can do it only in the component itself.

I hope it is clear enough.
Enrico

**Comment by macias** [comment]
As for the runtime I managed to fix it. My point was more along the old principle then when it is not required to upgrade packages it is better to keep them unchanged (i.e. upgrading for the sake of upgrading is not the best move), and runtime is more serious.

As for this `ctx` I am not sure if I can help but few points:
* I used also context and decided to pass to C# only minimal amount of data, not original context because it is too dynamic
* "The problem I faced was that the ctx properties are not available in the function" -- which function? On JS side or C# side?
* I noticed you used `DotNet.invokeMethodAsync` in JS callbacks. I am not JS/Blazor expert but I used synchronous method on purpose in my code -- this is because the async call is not awaited. In my case it would mean results would be lost, here you don't return the values, but still it may lead to some odd behaviour
* in your code you use variable name `ctx` quite a lot (for different purposes; I counted 3 -- canvas, callback parameter and local one). I prefer using distinct name so it is even easier for an eye to catch some bug related to getting/setting not the intended variable.

I would suggest just for testing -- pass only the data you need from `ctx`, use synchronous `Invoke`, use distinct names.

**Comment by erossini** [comment]
Thank you for your suggestion.

**Pull request merged**
