### PR TITLE
Implementation of beginAtZero, min & max properties for radar charts #73

### PR DESCRIPTION
**Pull request by sikelio**
Hi again i was waiting for the update in .NET 8, so here comes back my contributions to radar charts

Implemented the following properties for radar charts :
* beginAtZero
* min
* max

### CODE REVIEW

**Comment by erossini** [comment]
Thank you so much for your PR
Enrico

**Comment by erossini** [comment]
Haven't I updated the project? 😮

**Comment by sikelio** [comment]
Don't worry, you have updated the project to .NET 8 ^^
I was just refering to the initial goal of this PR :)

**Comment by sikelio** [comment]
Oupsi, I don't understand why there is a conflict :/
It seems you've added my PR before me x)

**Comment by erossini** [comment]
Yesterday I reorganized my code and made some changes in the past. I saw your PR and I added in my project some of your changes in particular for `Radar` to avoid errors. I think the conflicts are coming from the changes I have already made.

Sorry for the confusion.
Enrico

**Comment by sikelio** [comment]
No problem :)
So I can close the PR ?

**Comment by erossini** [comment]
Yes, thank you

**Pull request closed without merging**
